### ISSUE TITLE
What settings to use for blueSCSI to use with music sampler

### ISSUE THREAD

**Issue by audiogroove** [OneGeekArmy/Disk-Jockey-Community#14]
New at all this, would someone know what values I need to choose to get Disc Jockey to create SCSI images onto blueSCSI SD card?  
I need four 2G images to use in a sampling keyboard instrument called a kurzweil k2000.  
It is listed as a compatible device on the blueSCSI page.  When I try to just create the images with Disc Jockey I am creating them right to the sd card, I am choosing the SCSI ID and putting 2000 megabytes in the top window (probably should be 2048 I guess)  Anyway, my sampler writes only 1G and then the volume on the blueSCSI SD card image fails to write any more, gets scrambled and needs to be reformatted by the keyboard.  I can never surpass 1G written to the 2G image before it crashes again always at 1G.  

The specifications I need are four 2G SCSI hard drives emulated on IDs 1, 2, 3, and 4.  I have a 16G Sandisk SD card. Is there an important step I might be missing to get this all to work?  I have almost given up and have ordered a Zulu drive from a company that makes them specifically for samplers, but I would still like to get this blueSCSI to work so it's not a total waste.  I have a feeling I need to do something different for samplers than what you do for Macs.  But I have no idea.   

Thanks kindly for anyone that has any suggestions!

**Comment by OneGeekArmy** [comment]
Hi,

This is unintuitive, but you may want to try creating your images using Basilisk or Mini vMac as a target (instead of BlueSCSI).

The reason is that "Use with BlueSCSI" defines a device header and installs a SCSI driver for classic Macs on the disk image, which is really not what your sampler expects. Asking it to create it for Basilisk actually skips those steps and creates a simple, blank image that your sampler can then formats any way it wants.

Do however name the resulting disk image properly, according to the BlueSCSI format (HD_...) or BlueSCSI will be confused.

**Comment by AiGeekNet** [comment]
> Is there an app for windows that lets me see the contents of those image volumes and lets me just dump all my files in (including one level of subfolders) right in windows before I put the SD card back into the blue scsi ?

UltraISO can open hard disk image in RAW DD format  (the HDA just as it if you rename it to .IMG) and transfer files or directory.
