### ISSUE TITLE
Can the .HDA or .IMG image be directly mounted by OSX?

### ISSUE THREAD

**Issue by AiGeekNet** [OneGeekArmy/Disk-Jockey-Community#16]
I noticed that the hard disk image in RAW DD format can be directly mounted by OSX, which is very convenient for file exchange.

But the hard disk image in .HDA and .IMG format created by disk-jockey cannot be mounted. Can this problem be solved?

**Comment by OneGeekArmy** [comment]
That's because they are different things.

Images created with dd are _volume images_, containing a single partition that can be mounted by macOS. The images for BlueSCSI and PiSCSI that Disk Jockey creates are _device images_. People use "Disk Image" to talk about both kinds but they are different and should be distinguished better in my opinion.

I get into the details here:
[Some Technical Information](https://diskjockey.onegeekarmy.eu/help/technicalinfo/)

But the short version is this:
- Volume images (img) are very much like floppy disks: they contain a single partition with a single file system on it (could be HFS, FAT, ExFAT or anything). macOS knows how to mount these when you double-click on them.
- Device images (hda) represent the surface of an actual hard drive. This includes a device descriptor at the beginning, a partition map that lists the various partitions inside (each being like the contents of a volume image) and, very important for the Mac, a SCSI driver. macOS has no idea what these are, and cannot mount them natively.

Finally, the reason why macOS can't mount a volume image (img) created by Disk Jockey is that DJ creates unformatted volume images. This is because these volume images are meant to be formatted by whatever device or emulator you use it with. Once they are formatted, macOS can mount them just fine if it's a type of volume it knows, of course.

Hope this helps!
