### ISSUE TITLE
DiskOMatic problem showing contents of UTM-created .img

### ISSUE THREAD

**Issue by mabinog1an** [OneGeekArmy/Disk-Jockey-Community#28]
Thanks for creating this handy utility. Just passing along a problem I discovered:

In Disk Jockey v3.3 on a Mac, DiskOMatic (DoM) does not properly show the contents of a raw disk image that is newly created by UTM and then initialized by a guest virtual machine running OS 9.2.1.  SheepShaver is able to mount and use the contents of such a .img file without any problem. DoM can open and show the Device info -- except that where the Volume contents should be, DoM will instead show "Where_have_all_my_files_gone?". 

Attached is a zipped 200MB example of such an image that you can use with Disk Jockey (and SheepShaver) to see the problem. Its only contents are a text file created in SheepShaver with more info on how the image was created in UTM.
[DJnofiles.img.zip](https://github.com/user-attachments/files/15596254/DJnofiles.img.zip)

p.s. feature request:
It would be helpful if DoM prompted for a file name (with its recommendation as default) when converting images

**Comment by OneGeekArmy** [comment]
Hi!

Thanks for the question!

What you're seeing with "Where_have_all_my_files_gone?" is a very interesting historical artifact. This is what users would see when they tried to open an HFS+ (Mac OS Extended) volume on a machine that could only understand HFS volumes (this is explained a bit [here](https://en.wikipedia.org/wiki/HFS_Plus#Design) ).

This was done by systematically wrapping HFS+ volumes in an HFS wrapper that could be understood by older Macs.

DOM does not yet parse HFS+ volumes (but I'm literally putting the finishing touches to it as I write this) and so, as a good HFS citizen, it falls back on the HFS wrapper of your volume instead of showing you the HFS+ contents you expect.

So: not a bug, and it should be soon possible to get to the files you expect. Thanks for providing an image, by the way. It'll be an excellent test case for the new code.

As for your suggestion, it's great.
I'm moving away from dumping everything into the Downloads folder and presenting more dialog boxes to the users so this should arrive soon too.

Thanks for being a user! Hope this helps!

**Comment by mabinog1an** [comment]
Thank you for the kind and informative response -- and for working to add HFS+ capabilities going forward. Pursuing this gave me another tutorial on disk images beyond what your website's Help > Some Technical Information already provided. Previously, when initializing new disk images in either SheepShaver (at start-up) or UTM/QEMU (with Drive Setup), I hadn't explored beyond the default settings. Now I see that both are capable of initializing volumes as either HFS ("standard") or HFS+ ("extended"); but the former defaults to HFS and the latter to HFS+.
