### ISSUE TITLE
Disk-o-Matic: FAT12 floppy images can be read, but are always called Atari Images

### ISSUE THREAD

**Issue by elosha** [OneGeekArmy/Disk-Jockey-Community#31]
### Situation
I work a lot with various flavours of systems. Many use FAT12 floppies, especially of course DOS machines like IBM PCs and IBM PS/2s, all OS/2 and NT (including RISC) machines, NEC, even DEC Alphas rely on them for booting. Additionally, FAT12 is a widely supported exchange FS on IBM formatted floppies.

### Issue
Originally there were MS-DOS floppies but Disk-o-Matic presents them with a strong Atari branding, because besides all those systems, Atari ST uses them, too ;) I see Disk Jockey doesn't yet support all the other systems, but I guess at some point there will be a PC-style support, since that incorporates too many interesting SCSI machines.

### Some resolution ideas
- Check the file extension: Non-Atari floppies never use the ".st" extension 😁 
- Check the OEM string in the boot sector: It is set according to the OS while formatting, for example `MSDOS5.0`. Then present the image in an appropriate style.
- Use a generic "FAT12", "IBM-style" or "DOS format" branding (following how back in the days you could buy 3.5" floppies either in "DOS" or "Macintosh" format) for all FAT12 images.

**Comment by OneGeekArmy** [comment]
Hi - sorry for the late reply.

You're totally right of course, FAT12 is pretty much (but not always) the same whether it's TOS or DOS.

I haven't done much testing with PC floppies at all and, while they should be working fine, I don't want to give the impression that it's a supported format yet. It's coming, but I wanted to focus on the ST first.

As for your idea (all good!):
- File extension: I make it a principle that DJ will not use the extension as a hint to detect what the image is (we'll see how long that principle survives). Instead, it parses the contents and deduces what it is by looking at the various possibilities (it's not AI, it's good old-fashioned testing :p). So that's not a path I'm willing to take.
- OEM string: yes absolutely. That fits with my approach. I want to integrate this properly and there is a lot of partition IDs in MBR (https://en.wikipedia.org/wiki/Partition_type). Might as well be precise with the detection :)
- I'd rather be specific instead of providing a general.

So, approach 2 is the way I'll go.

Thanks for your interest in DJ and your suggestion!
